# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('initial_nama', models.CharField(max_length=5)),
                ('prodi', models.CharField(choices=[('Business Mathematic (BM)', 'Business Mathematic (BM)'), ('Renewable Energy Engineering (REE)', 'Renewable Energy Engineering (REE)'), ('Food Business Technology (FBT)', 'Food Business Technology (FBT)'), ('Product Design Engineering (PDE)', 'Product Design Engineering (PDE)'), ('Software Engineering (SE)', 'Software Engineering (SE)'), ('Computer Systems Engineering (CSE)', 'Computer Systems Engineering (CSE)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('kode_ruang', models.CharField(max_length=30)),
                ('gedung', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kuliah', models.CharField(max_length=50)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat')], default='Senin', max_length=6)),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('prodi', models.CharField(choices=[('Business Mathematic (BM)', 'Business Mathematic (BM)'), ('Renewable Energy Engineering (REE)', 'Renewable Energy Engineering (REE)'), ('Food Business Technology (FBT)', 'Food Business Technology (FBT)'), ('Product Design Engineering (PDE)', 'Product Design Engineering (PDE)'), ('Software Engineering (SE)', 'Software Engineering (SE)'), ('Computer Systems Engineering (CSE)', 'Computer Systems Engineering (CSE)')], max_length=50)),
                ('kode_prodi', models.CharField(choices=[('BM', 'BM'), ('REE', 'REE'), ('FBT', 'FBT'), ('PDE', 'PDE'), ('SE', 'SE'), ('CSE', 'CSE')], max_length=3)),
                ('faculty', models.CharField(choices=[('STEM', 'STEM'), ('SBE', 'SBE')], max_length=40)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Room'),
        ),
    ]
