# Generated by Django 2.2.7 on 2020-01-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewKuliahRevise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('program_id', models.CharField(blank=True, max_length=20, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_id', models.CharField(blank=True, max_length=20, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=20, null=True)),
                ('event_obj', models.CharField(blank=True, max_length=20, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('nik', models.CharField(blank=True, max_length=5, null=True)),
                ('faculty_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewKuliah',
        ),
    ]
