# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20190211_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_end',
            field=models.DateField(blank=True, help_text='Day end of the event', null=True, verbose_name='Day end of the event'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date_start',
            field=models.DateField(blank=True, help_text='Day start of the event', null=True, verbose_name='Day start of the event'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='initial_nama',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='kode_ruang',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='nama_kuliah',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
