# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20190213_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nama_ruang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='schedules.Lecturer'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='schedules.Student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruang', to='schedules.Room'),
        ),
    ]
