# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20190814_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_at',
            field=models.TimeField(max_length=40),
        ),
    ]
