# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_auto_20190814_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='gedung',
            field=models.CharField(choices=[('STEM Lab', 'STEM Lab'), ('Gedung Liem', 'Gedung Liem')], max_length=50),
        ),
    ]
