# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_auto_20190814_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomslot',
            name='jumlah_sks',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=3),
            preserve_default=False,
        ),
    ]
