# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_roomslot_jumlah_sks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomslot',
            name='jumlah_sks',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3),
        ),
    ]
