# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_auto_20190814_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalHarian',
            fields=[
                ('nama_mata_kuliah', models.CharField(max_length=40)),
                ('jumlah_sks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=3)),
                ('room_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schedules.RoomSlot')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='schedules.Lecturer')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiwa', to='schedules.Student')),
            ],
        ),
    ]
