# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_jadwalharian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalharian',
            name='nama_mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matakuliah', to='schedules.MataKuliah'),
        ),
    ]
