# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_auto_20190814_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalharian',
            name='room_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='roomslot', serialize=False, to='schedules.RoomSlot'),
        ),
    ]
