# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-28 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0023_room_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='jenis',
            field=models.CharField(choices=[('Kelas', 'Kelas'), ('Lab VLAB', 'Lab VLAB'), ('Lab Non-VLAB', 'Lab Non-VLAB')], max_length=30),
        ),
    ]
