# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-28 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0025_auto_20190828_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='jenis_ruang',
            new_name='jenis',
        ),
    ]
