# Generated by Django 2.2.6 on 2019-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0027_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuliah',
            name='class_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kuliah',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kuliah',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='kuliah',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
