# Generated by Django 2.2.7 on 2020-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0029_newkuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='newkuliah',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
