# Generated by Django 2.2.7 on 2020-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0030_newkuliah_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newkuliah',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
